logger:
  file:
    path: /var/log/open5gs/smf.log
#  level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
    ue: 1024  # The number of UE can be increased depending on memory size.
#    peer: 64

smf:
  sbi:
    server:
      - address: 127.0.0.4
        port: 7777
    client:
      nrf:
        - uri: http://127.0.0.10:7777
      scp:
        - uri: http://127.0.0.200:7777
      pcf:
        - uri: http://127.0.0.13:7777
  pfcp:
    server:
      - address: 192.168.64.110
    client:
      upf:
        - address: 192.168.64.40
  gtpc:
    server:
      - address: 127.0.0.4
  gtpu:
    server:
      - address: 192.168.64.110
  metrics:
    server:
      - address: 192.168.64.110
        port: 9090
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dnn: internet
#    - subnet: 2001:db8:cafe::/48
 #     gateway: 2001:db8:cafe::1
  dns:
    - 8.8.8.8
    - 8.8.4.4
    - 2001:4860:4860::8888
    - 2001:4860:4860::8844
  mtu: 1400
#  p-cscf:
#    - 127.0.0.1
#    - ::1
#  ctf:
#    enabled: auto   # auto(default)|yes|no
  freeDiameter: /etc/freeDiameter/smf.conf
  info:
    - s_nssai:
        - sst: 1
          sd: 000001
          dnn:
            - internet
      tai:
        - plmn_id:
            mcc: 999
            mnc: 70
          tac: 1
